FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app

COPY --from=build /app .

# create output dir for the refactoring output generated by the tool
RUN mkdir -p /app/Output

# copy over the detectors to use in the tool
COPY Detectors /app/Detectors

# update, and then install jdk, maven, wget and tar
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        openjdk-17-jdk maven wget tar \
        ca-certificates && \
    apt-get clean && \
    update-ca-certificates

# download, unpack and cleanup latest codeql bundle (includes language libraries) for linux
RUN wget -q https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz -O /tmp/codeql.tar.gz && \
    tar -xf /tmp/codeql.tar.gz --directory /usr/local && \
    rm /tmp/codeql.tar.gz

ENV PATH="/usr/local/codeql:${PATH}"

ENTRYPOINT ["dotnet", "RefactorGuidanceTool.dll"]
CMD ["/app/Output", "/app/Detectors"]